apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ExternalName
  externalName: localhost # Replace with your actual hostname or IP where nodeapp4 is running
  ports:
    - protocol: TCP
      port: 8080 # Port your application is running on
