apiVersion: v1
kind: Service
metadata:
  name: nodeapp4-service
spec:
  type: NodePort # Use NodePort or LoadBalancer as per your setup
  selector:
    app: nodeapp4
  ports:
    - protocol: TCP
      port: 8080 # Port exposed by your Node.js application
      targetPort: 8080 # Port your Node.js application is listening on
